### ISSUE TITLE
Bot Login - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by nikebooom** [joe27g/EnhancedDiscord-Plugins#13] opened 2019-09-03 12:27 UTC
makes my discord not work at all https://gyazo.com/409fa9117337c01c5118a9c02e5d4187

**Comment by ThatLifeofGames** [comment] 2019-09-03 12:35
Literally a dupe of #12, the only other issue here...

**Comment by joe27g** [comment] 2019-09-03 12:40
What he said, + I'm going to close all Discord Source issues from now on. Like this one, they are usually pointless and/or duplicates.

**Closed by joe27g** 2019-09-03 12:40 UTC
